/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ddb-gt": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "global-table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
